### ISSUE TITLE
same position for multiple message

### ISSUE THREAD

**Issue by nimatullah** [dolce/iziToast#130]
When I click on success multiple time, it creates multiple messages and appends it on the bottom of last.

What I want is to replace the first message with the second message.

Can I do that?

Does it have any option for it?

It should replace the old message with the new message in the same position.

Because when I call an APIs if an error occurred it displays all error appended to each other which looks ugly.
![izitoast](https://user-images.githubusercontent.com/3712526/38766806-afb2e2e0-3fec-11e8-9cc9-c2bff8392ef5.png)

**Comment by nimatullah** [comment]
@dolce

**Comment by nimatullah** [comment]
Hello guys, I need an answer.

**Comment by dolce** [comment]
Hello @nimatullah.
Do you want the Toast to be displayed only once?

**Comment by dolce** [comment]
It is only you to use the properties below, remembering what this has in the documentation.
```
iziToast.show({
    title: 'Hello!',
    id: 'toast', 
    toastOnce: true
});
```

**Comment by nimatullah** [comment]
What I mean is that it should not append to the last one. It should replace it. Or perhaps a different approach to solving the problem, the same toast keep appearing and this is bad user experience. I am open to any suggestions.
![imageedit_2_4082029562](https://user-images.githubusercontent.com/3712526/39953865-e9769da8-55c9-11e8-9410-a9c8173c5b91.png)

In above attachment, when I click on save job, it saves the job, after clicking the save button multiple time, it appends it to the last message.

**Comment by dolce** [comment]
If you do not want it to be opened multiple times then at the moment I advise you to use the toastOnce property as I mentioned above.

**Comment by dolce** [comment]
If you don't want it to be opened multiple times then at the moment I advise you to use the toastOnce property as I mentioned above.

**Comment by cytec** [comment]
I've came across the same problem lately. 
So i have a site which sends you multiple different notifications over a short period of time ex you klick a button and then you'll get 4 notifications (whenever they are send back by the server):

Startet process 1
Started process 2
Finished process 2
Finished process 1

Currently they are appended like @nimatullah shows in his image is there any way that the following toasts update/replace the existing one instead of appending them?

**Comment by cytec** [comment]
@dolce is there any way to do something like that?

**Comment by dolce** [comment]
How would you call this new option?
`replaceToast: true`
?

**Comment by dolce** [comment]
@cytec , @nimatullah 
How would you call this new option?

```js
toastOnce: false,
replaceToast: false,
```
or
```js
displayMode: false // or 'once', 'replace'
```
can also be: 0(false), 1(once), 2(replace)

**Comment by cytec** [comment]
@dolce im fine with either way.

I guess the first option `replaceToast` would be a bit more compatible since if i get that correct option 2 would change the api for `toastOnce` as well?

**Comment by cytec** [comment]
@dolce wouldn't it be possible to combine those two options? so that both can be true?
not entirely sure if i recall that correctly but `toastOnce` was the option to wait till the last message was closed before showing the new one? if thats correct and `replaceToast` just replaces the already placed toast as noted above, setting both to true would be some sort of message queue?

If thats true i guess keeping 2 options would make sense, if not... personally i think both ways would fit and you should use the one you think fits best.

**Comment by dolce** [comment]
[iziToast v1.3.1.zip](https://github.com/dolce/iziToast/files/2216507/iziToast.v1.3.1.zip)
Could you test?
```js
displayMode: false // 'once', 'replace'

displayMode: 0 // 1, 2
```

**Comment by cytec** [comment]
seems to work as it should 👍

**Comment by dolce** [comment]
v1.4.0 released.
https://www.npmjs.com/package/izitoast
