### ISSUE TITLE
utf-8 support ? "InvalidCharacterError: String contains an invalid character"

### ISSUE THREAD

**Issue by alirezaimi** [dolce/iziToast#148]
Hi
Is your code support utf-8 chars like this code ? :

	iziToast.show({
		title: '...',
		message: "در حال یافتن",
		rtl: true
	});

The above code show this error :

    InvalidCharacterError: String contains an invalid character

**Comment by ap-prog** [comment]
The following page worked fine for me in Chrome, Edge, IE10, and Firefox - the dialog correctly appeared with RTL text...

`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Test</title>
<link type="text/css" rel="stylesheet" href="iziToast.min.css">
<script src="iziToast.min.js"></script>
<script>
window.onload = function() {
  iziToast.question({
  	title: '...',
  	message: "در حال یافتن",
  	rtl: true
  });
};
</script>
</head>
<body>
<p>&nbsp;</p>
</body>
</html>`

**Comment by dolce** [comment]
Yes, it works normally.
```
iziToast.show({
    message: "در حال یافتن",
    rtl: true
});
```

**Comment by alirezaimi** [comment]
not work for me :(
in firefox :
`InvalidCharacterError: String contains an invalid character`
in chrome :
`Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`

**Comment by alirezaimi** [comment]
any ideas ?

**Comment by realvee** [comment]
@alirezaimi   there's a bug in the line 653.
var newId = btoa(settings.title+settings.message+settings.color);

It may not be actually a bug, but developer may not aware of UTF-8 text. 
Since btoa accepts only ASCII, so for this, you need to put "encodeURIComponent" in iziToast.js line 653

var newId = btoa(encodeURIComponent(settings.title+settings.message+settings.color));

and it'll work just fine.

**Comment by dolce** [comment]
Fixed, will be published soon, thank you.

**Comment by dolce** [comment]
v1.4.0 released.
https://www.npmjs.com/package/izitoast
